# This is a basic example Blueprint for a Django web service and
# the PostgreSQL database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: cacticards-app
    runtime: node
    repo: https://github.com/Burgersim/CactiCards.git
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: cacticards-app-db
          property: connectionString

databases:
  - name: cacticards-app-db # A PostgreSQL database named django-app-db running on a free instance
    plan: free
